### ISSUE TITLE
Fixed userbar on top of the page and missing hover up button

### ISSUE THREAD

**Issue by cgunes** [vbresults/mobile-apps#69]
### 1.2. Which platform(s) does your issue occur on?
Both

### 1.3. Version numbers that your issue occurs with:
- iOS App: (e.g. 1.2.0)
- Android App: (e.g. 1.2.0)
- XenForo Version: (e.g. 1.5.5)

### 3.1. If so, enter your question

1) Is it possible to make the user bar stay fixed on top of the page. I mean even when the users scroll down the page , the user bar "Main navigation menu" always stays visible in a fixed position on top of the page.
2) The hover up button (The button which is visible in the bottom right corner of the page when you scroll to the bottom) does not appear in the app , even though it is enabled in the style.

**Comment by vbresults** [comment]
The iOS app doesn't support fixed CSS positions but we are very close to a fix, and it will likely be out in the next version (:

**Comment by vbresults** [comment]
The iOS app doesn't support fixed CSS positions (which is what the "sticky" features you mention are powered by) but we are very close to a fix, and it will likely be out in the next version (:

BTW, if you are experiencing this on Android too, please confirm because it shouldn't be happening there

Ping @bloh2 @DanHawk87

**Comment by vbresults** [comment]
Confirmed fixed in the next version! (:

**Comment by cgunes** [comment]
Yes ,we are experiencing it on Android too.  We have sticky menu feature enabled with UI.X  , but it doesn't work in the android app also. The theme is audentio xenblock.

**Comment by vbresults** [comment]
Android turns out to have been affected by the same issue for some apps (though this wasn't consistent across all of them) -- but it's fixed in the latest version soon to be released

**Comment by cgunes** [comment]
Thank you

**Comment by cgunes** [comment]
Still experiencing the same problem with new update 1.2.31
Sticky menu doesn't work in both Android and IOS apps.

Sticky menus works with mobile browsers ie. safari

**Comment by vbresults** [comment]
@king8084 You mentioned sticky features not working for you too so I'm alerting you of this ticket; we're working on this

**Comment by vbresults** [comment]
Found out a totally separate issue that caused this problem to come back after it was taken care of.  Fortunately, fixing it this time does not require an app update;

this is an instant fix -- to apply an instant fix, go to the add-on settings, find the "Cache Reset" setting, hit the + symbol, and Save (:

**Comment by cgunes** [comment]
Sticky menus work now :)   But when the screen goes landscape , the menu looses sticky function

**Comment by vbresults** [comment]
@cgunes Please open a separate ticket for this with the details about the platforms it occurs on

**Comment by cgunes** [comment]
Ok , I will test and report back.
Thank you

**Comment by cgunes** [comment]
It also happens in Safari browser , this must be a UI.X template issue .
